// Generated by CoffeeScript 1.6.3
(function() {
  var Configuration, DI, DIConfigurator;

  DI = require('./DI');

  Configuration = require('easy-configuration');

  DIConfigurator = (function() {
    DIConfigurator.prototype.path = null;

    DIConfigurator.prototype.defaultService = {
      service: null,
      "arguments": [],
      instantiate: true,
      autowired: true,
      run: false,
      setup: {}
    };

    function DIConfigurator(path) {
      this.path = path;
    }

    DIConfigurator.prototype.create = function() {
      var config, data, defaults, di, method, name, run, s, service, services, _i, _len, _ref;
      config = new Configuration(this.path);
      defaults = this.defaultService;
      services = config.addSection('services');
      services.loadConfiguration = function() {
        var name;
        config = this.getConfig();
        for (name in config) {
          config[name] = this.configurator.merge(config[name], defaults);
        }
        return config;
      };
      data = config.load().services;
      di = new DI;
      run = [];
      for (name in data) {
        service = data[name];
        s = di.addService(name, service.service, service["arguments"]);
        s.setInstantiate(service.instantiate);
        s.setAutowired(service.autowired);
        _ref = service.setup;
        for (method in _ref) {
          arguments = _ref[method];
          s.addSetup(method, arguments);
        }
        if (service.run === true) {
          run.push(name);
        }
      }
      for (_i = 0, _len = run.length; _i < _len; _i++) {
        name = run[_i];
        di.getByName(name);
      }
      return di;
    };

    return DIConfigurator;

  })();

  module.exports = DIConfigurator;

}).call(this);
